### ISSUE TITLE
error

### ISSUE THREAD

**Issue by quattrinia** [brunoasm/usnps_to_nexus#1]
Hi there,

I tried using your script, but I did get this error:
Traceback (most recent call last):
  File "unlinked_snps_to_nexus.py", line 98, in <module>
    column_list = [recode_to_snapp(alignment[:,i]) for i in xrange(len(alignment[0]))]
NameError: name 'xrange' is not defined

Any advice? 

Thanks

**Comment by brunoasm** [comment]
Hi @quattrinia, thanks for the question.

It seems **xrange** does not exist in Python 3 (I wrote the script for Python 2)

You can either run the script with Python 2 or replace all instances of **xrange** with **range** and run with Python 3. However, there might be some other incompatibilities, since I never tested the script on Python 3.

**Comment by quattrinia** [comment]
Thanks~
I used 2to3 to fix the code and it worked. However, I did get this error
unlinked_snps_to_nexus.py:42: UserWarning: Alignment column with >2 alleles removed
  warn('Alignment column with >2 alleles removed')

It wrote a new file with 2 SNPs less than the original .phyl file. I need to look through it to see if all else worked ok.

**Comment by brunoasm** [comment]
Hi @quattrinia, at least the last time I used, SNAPP only worked with biallelic SNPS.
In some cases, the input file may contain alignment columns with more than 2 alleles. When this happens, this column is removed and a warning is raised.

The warning is repeated each time a column with more than two alleles is found (which is something I should probably improve at some point, and just report the number of columns removed).

I hope this helps!

Bruno
